_commit: v0.4.2
_src_path: https://github.com/will-rice/papers-template.git
project_name: TTS Papers
project_slug: tts-papers
template_version: 0.1.0
topic_description: Text-to-speech research papers
